"""Deterministic offline A-share backtest primitives."""

from stock_quant.backtest.account import (
    AccountError,
    AccountState,
    AccountValuation,
    book_buy,
    book_sell,
    MissingValuationError,
    Position,
    PositionLot,
    RawMark,
    StaleValuationError,
    TradeAccountingEntry,
    value_account,
)
from stock_quant.backtest.actions import (
    ActionIntegrationState,
    apply_pre_market_action,
    capture_record_entitlement,
    EligibleQuantitySnapshot,
)
from stock_quant.backtest.constraints import (
    ConstraintDecision,
    OrderSide,
    RejectionCode,
    SuspensionConstraint,
)
from stock_quant.backtest.costs import (
    calculate_trading_costs,
    TradingCostBreakdown,
    TradingCostRule,
    TradingCostSchedule,
)
from stock_quant.backtest.timeline import (
    DeterministicTimeline,
    EventKind,
    EventPhase,
    TimelineConflictError,
    TimelineEvent,
)
from stock_quant.backtest.limits import (
    evaluate_price_limit,
    fill_price_within_limits,
    PriceLimitBand,
    PriceLimitRule,
    PriceLimitSchedule,
)
from stock_quant.backtest.execution import (
    execute_next_open,
    ExecutionOutcome,
    Fill,
    OrderIntent,
    SlippageModel,
)
from stock_quant.backtest.rebalance import (
    create_rebalance_intent,
    plan_rebalance,
    RebalanceIntent,
    RebalancePlan,
    TargetWeight,
)
from stock_quant.backtest.result import (
    BacktestResult,
    create_backtest_result,
    EquityPoint,
    HoldingSnapshot,
    RejectionRecord,
    ReplayIdentityError,
    verify_backtest_result,
)
from stock_quant.backtest.t1 import (
    credit_corporate_action_lot,
    require_sellable,
    sellable_quantity,
    T1SellabilityError,
)

__all__ = [
    "DeterministicTimeline",
    "AccountError",
    "AccountState",
    "AccountValuation",
    "ActionIntegrationState",
    "apply_pre_market_action",
    "book_buy",
    "book_sell",
    "BacktestResult",
    "calculate_trading_costs",
    "capture_record_entitlement",
    "credit_corporate_action_lot",
    "ConstraintDecision",
    "create_rebalance_intent",
    "create_backtest_result",
    "EventKind",
    "execute_next_open",
    "ExecutionOutcome",
    "EligibleQuantitySnapshot",
    "EquityPoint",
    "EventPhase",
    "evaluate_price_limit",
    "fill_price_within_limits",
    "Fill",
    "HoldingSnapshot",
    "MissingValuationError",
    "OrderSide",
    "OrderIntent",
    "Position",
    "PositionLot",
    "plan_rebalance",
    "PriceLimitBand",
    "PriceLimitRule",
    "PriceLimitSchedule",
    "RawMark",
    "RebalanceIntent",
    "RebalancePlan",
    "RejectionCode",
    "RejectionRecord",
    "ReplayIdentityError",
    "require_sellable",
    "sellable_quantity",
    "SlippageModel",
    "StaleValuationError",
    "SuspensionConstraint",
    "TimelineConflictError",
    "T1SellabilityError",
    "TimelineEvent",
    "TargetWeight",
    "TradeAccountingEntry",
    "TradingCostBreakdown",
    "TradingCostRule",
    "TradingCostSchedule",
    "value_account",
    "verify_backtest_result",
]
